### ISSUE TITLE
Specify shader source path

### ISSUE THREAD

**Issue by Khhs167** [sinnwrig/Glslang.NET#1]
Hi! Just discovered this wonderful library.

I'm wondering if you have any way to specify the source file, either via the `CompilationInput` or via some method on the `Shader`?

I suppose that is how we're expected to use the fileIncluder? Or should it be unique on a per-shader basis?

**Comment by sinnwrig** [comment]
Hi, I believe at the moment the API has  `Program.SetSourceFile` to set the source file name of a specific program stage when creating a program. However, I'm not sure this will do exactly what you need. I believe the current glslang version in the package does not expose it in the C interop API.

However, I am in the middle of modifying the fork of glslang used for this wrapper to expose more of the C++ interface, which does expose `Shader.SetSourceFile` (along with some HLSL parsing fixes and niceties). I'll be sticking these additions in ver. 1.2 of the package, which I'll be uploading in a few days.

**Comment by sinnwrig** [comment]
After looking at glslang source, it doesn't seem like `SetSourceFile` appropriately names the source include file, and instead is related to the `__FILE__` and `__LINE__` GLSL preprocessor directives. However, a reliable workaround to check if a file is from source or not is to check if its name is null or whitespace. I do this [here](https://github.com/ProwlEngine/Prowl/blob/58ca8c6384ef81c6e0867ad24350a07658442fc7/Prowl.Editor/Utilities/ShaderCompiler/FileIncluder.cs#L49), and as of writing it's proven to be reliable.
